---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/govc version
    register: govc_test_output
  - name: govc version
    debug:
      msg: '{{ govc_test_output.stdout }}'
