---
- name: Testing andrewrothstein.govc
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'govc --version'
      ansible.builtin.command: /usr/local/bin/govc version
      changed_when: false
      register: govc_test_output
    - name: Output of 'govc version'
      ansible.builtin.debug:
        msg: '{{ govc_test_output.stdout }}'
