---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Look for installed executable at {{ govc_install_exe }}
  become: true
  ansible.builtin.stat:
    path: '{{ govc_install_exe }}'
  changed_when: false
  register: govc_binary
- name: Downloading and installing govc
  when: not govc_binary.stat.exists
  block:
    - name: Downloading {{ govc_url }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ govc_url }}'
        dest: '{{ govc_tmp_archive }}'
        checksum: '{{ govc_checksum }}'
        timeout: '{{ govc_dl_timeout }}'
        mode: '644'
    - name: Mkdir {{ govc_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ govc_install_dir }}'
        state: directory
        mode: '755'
    - name: Unarchive {{ govc_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ govc_tmp_archive }}'
        dest: '{{ govc_install_dir }}'
        creates: '{{ govc_install_exe }}'
  always:
    - name: Rm {{ govc_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ govc_tmp_archive }}'
        state: absent
- name: Linking {{ govc_link_exe }} to {{ govc_install_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ govc_install_exe }}'
    dest: '{{ govc_link_exe }}'
    state: link
