---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: look for install
  become: yes
  stat:
    path: '{{ govc_install_exe }}'
  changed_when: False
  register: govc_binary
- when: not govc_binary.stat.exists
  block:
    - name: download
      become: yes
      become_user: root
      get_url:
        url: '{{ govc_url }}'
        dest: '{{ govc_install_dir }}/{{ govc_ver_gz }}'
        checksum: '{{ govc_checksum }}'
        mode: 0644
    - name: gunzip
      become: yes
      become_user: root
      command: 'gunzip {{ govc_ver_gz }}'
      args:
        chdir: '{{ govc_install_dir }}'
        creates: '{{ govc_install_exe }}'
    - name: make executable
      become: yes
      become_user: root
      file:
        path: '{{ govc_install_exe }}'
        mode: 0755
- name: link
  become: yes
  become_user: root
  file:
    src: '{{ govc_install_exe }}'
    dest: '{{ govc_link_exe }}'
    state: link
