---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: look for installed executable at {{ govc_install_exe }}
  become: yes
  stat:
    path: '{{ govc_install_exe }}'
  changed_when: False
  register: govc_binary
- when: not govc_binary.stat.exists
  block:
    - name: downloading {{ govc_url }}
      become: yes
      become_user: root
      get_url:
        url: '{{ govc_url }}'
        dest: '{{ govc_tmp_archive }}'
        checksum: '{{ govc_checksum }}'
        mode: 0644
    - name: mkdir {{ govc_install_dir }}
      become: yes
      become_user: root
      file:
        path: '{{ govc_install_dir }}'
        state: directory
        mode: 0755
    - name: unarchive {{ govc_tmp_archive }}
      become: yes
      become_user: root
      unarchive:
        remote_src: yes
        src: '{{ govc_tmp_archive }}'
        dest: '{{ govc_install_dir }}'
        creates: '{{ govc_install_exe }}'
  always:
    - name: rm {{ govc_tmp_archive }}
      become: yes
      become_user: root
      file:
        path: '{{ govc_tmp_archive }}'
        state: absent
- name: linking {{ govc_link_exe }} to {{ govc_install_exe }}
  become: yes
  become_user: root
  file:
    src: '{{ govc_install_exe }}'
    dest: '{{ govc_link_exe }}'
    state: link
